// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQb_cB9RcHy6dIsiIOc8ZnJwvnZwyNnE',
    appId: '1:448696791874:web:68dac79b3b6f279a714edb',
    messagingSenderId: '448696791874',
    projectId: 'motherly-1877f',
    authDomain: 'motherly-1877f.firebaseapp.com',
    storageBucket: 'motherly-1877f.firebasestorage.app',
    measurementId: 'G-L8CMVTHNRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVLQmrVZy9EiDpgtoiojEZYWM0tFrAVM',
    appId: '1:448696791874:android:6a54058217440227714edb',
    messagingSenderId: '448696791874',
    projectId: 'motherly-1877f',
    storageBucket: 'motherly-1877f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJK5L3axTXbOGCkluVPKhCGQNtVgbl3dA',
    appId: '1:448696791874:ios:e6509b36daa671ad714edb',
    messagingSenderId: '448696791874',
    projectId: 'motherly-1877f',
    storageBucket: 'motherly-1877f.firebasestorage.app',
    iosBundleId: 'com.example.motherlyV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJK5L3axTXbOGCkluVPKhCGQNtVgbl3dA',
    appId: '1:448696791874:ios:e6509b36daa671ad714edb',
    messagingSenderId: '448696791874',
    projectId: 'motherly-1877f',
    storageBucket: 'motherly-1877f.firebasestorage.app',
    iosBundleId: 'com.example.motherlyV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQb_cB9RcHy6dIsiIOc8ZnJwvnZwyNnE',
    appId: '1:448696791874:web:43d8ee57381c41cb714edb',
    messagingSenderId: '448696791874',
    projectId: 'motherly-1877f',
    authDomain: 'motherly-1877f.firebaseapp.com',
    storageBucket: 'motherly-1877f.firebasestorage.app',
    measurementId: 'G-L433KD7HFE',
  );
}
